const std = @import("std");

pub const mongo_config_files = .{
    "mongoc-config.h",
    "mongoc-version.h",
};

const CFLAGS = &.{ "-std=c23", "-pthread" };

pub fn addMongoToLibrary(
    b: *std.Build,
    lib: *std.Build.Step.Compile,
    upstream: *std.Build.Dependency,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
) !*std.Build.Module {
    const mongo_mod = b.addModule("mongoc", .{
        .root_source_file = b.path("src/mongo.zig"),
        .target = target,
        .optimize = optimize,
    });

    mongo_mod.addCSourceFiles(.{
        .files = mongo_src_files,
        .flags = CFLAGS,
        .root = upstream.path("src/libmongoc/src/mongoc"),
    });

    mongo_mod.addIncludePath(upstream.path("src/common/src"));
    mongo_mod.addIncludePath(upstream.path("src/libbson/src"));
    mongo_mod.addIncludePath(upstream.path("src/libmongoc/src"));
    mongo_mod.addIncludePath(upstream.path("src/uthash/"));
    mongo_mod.addIncludePath(upstream.path("src/utf8proc-2.8.0/"));
    mongo_mod.addIncludePath(upstream.path("src/kms-message/src"));

    mongo_mod.addCMacro("BSON_COMPILATION", "1");
    mongo_mod.addCMacro("MONGOC_COMPILATION", "1");

    if (target.result.os.tag == .linux) {
        mongo_mod.addCMacro("_POSIX_C_SOURCE", "200809L");
        mongo_mod.addCMacro("_GNU_SOURCE", "1");
        //bson_mod.linkSystemLibrary("pthread", .{});
    }

    inline for (mongo_config_files) |_header| {
        const tmp = b.addConfigHeader(
            .{
                .style = .{ .cmake = upstream.path("src/libmongoc/src/mongoc/" ++ _header ++ ".in") },
                .include_path = "mongoc/" ++ _header,
            },
            .{
                .libmongoc_VERSION_MAJOR = 2,
                .libmongoc_VERSION_MINOR = 0,
                .libmongoc_VERSION_PATCH = 1,
                .libmongoc_VERSION_FULL = .@"2.0.1",
                .libmongoc_VERSION_PRERELEASE = null,
                .MONGOC_USER_SET_CFLAGS = .@"-pthreads",
                .MONGOC_USER_SET_LDFLAGS = .@"-pthreads",
                .MONGOC_CC = .clang,
                .MONGOC_ENABLE_SSL_SECURE_CHANNEL = 0,
                .MONGOC_ENABLE_CRYPTO_CNG = 0,
                .MONGOC_HAVE_BCRYPT_PBKDF2 = 1,
                .MONGOC_ENABLE_SSL_SECURE_TRANSPORT = 1,
                .MONGOC_ENABLE_CRYPTO_COMMON_CRYPTO = 0,
                .MONGOC_ENABLE_SSL_OPENSSL = 0, //Use system's SSL implementation
                .MONGOC_ENABLE_CRYPTO_LIBCRYPTO = 0,
                .MONGOC_ENABLE_SSL = 1,
                .MONGOC_ENABLE_CRYPTO = 1,
                .MONGOC_ENABLE_CRYPTO_SYSTEM_PROFILE = 0,
                .MONGOC_HAVE_ASN1_STRING_GET0_DATA = 1,
                .MONGOC_ENABLE_SASL = 0,
                .MONGOC_ENABLE_SASL_CYRUS = 0,
                .MONGOC_ENABLE_SASL_SSPI = 0, //TODO: Work on Windows build
                .MONGOC_HAVE_SASL_CLIENT_DONE = 0,
                .MONGOC_HAVE_SOCKLEN = 1,
                .MONGOC_ENABLE_SRV = 1,
                .MONGOC_HAVE_DNSAPI = 0, //TODO: Work on Windows build
                .MONGOC_HAVE_RES_NSEARCH = 1,
                .MONGOC_HAVE_RES_NDESTROY = 1,
                .MONGOC_HAVE_RES_NCLOSE = 1,
                .MONGOC_HAVE_RES_SEARCH = 1,
                .MONGOC_SOCKET_ARG2 = .int,
                .MONGOC_SOCKET_ARG3 = .socklen_t,
                .MONGOC_ENABLE_COMPRESSION = 1,
                .MONGOC_ENABLE_COMPRESSION_SNAPPY = 0,
                .MONGOC_ENABLE_COMPRESSION_ZLIB = 1,
                .MONGOC_ENABLE_COMPRESSION_ZSTD = 0,
                .MONGOC_ENABLE_SHM_COUNTERS = 0,
                .MONGOC_ENABLE_RDTSCP = 0, //Fails on ARM systems
                .MONGOC_HAVE_SCHED_GETCPU = 0, //Fails on ARM systems
                .MONGOC_TRACE = 1,
                .MONGOC_ENABLE_CLIENT_SIDE_ENCRYPTION = 0, //TODO: Find a way to enable client side encryption
                .MONGOC_HAVE_SS_FAMILY = 1,
                .MONGOC_ENABLE_MONGODB_AWS_AUTH = 1, //Disable AWS Auth for now
            },
        );
        lib.installConfigHeader(tmp);
        mongo_mod.addConfigHeader(tmp);
    }

    return mongo_mod;
}

pub const mongo_header_files = &.{
    "mcd-azure.h",
    "mcd-integer.h",
    "mcd-nsinfo.h",
    "mcd-rpc.h",
    "mcd-time.h",
    "mongoc-aggregate-private.h",
    "mongoc-apm-private.h",
    "mongoc-apm.h",
    "mongoc-array-private.h",
    "mongoc-async-cmd-private.h",
    "mongoc-async-private.h",
    "mongoc-buffer-private.h",
    "mongoc-bulk-operation-private.h",
    "mongoc-bulk-operation.h",
    "mongoc-change-stream-private.h",
    "mongoc-change-stream.h",
    "mongoc-client-pool-private.h",
    "mongoc-client-pool.h",
    "mongoc-client-private.h",
    "mongoc-client-session-private.h",
    "mongoc-client-session.h",
    "mongoc-client-side-encryption-private.h",
    "mongoc-client-side-encryption.h",
    "mongoc-client.h",
    "mongoc-cluster-aws-private.h",
    "mongoc-cluster-cyrus-private.h",
    "mongoc-cluster-private.h",
    "mongoc-cluster-sasl-private.h",
    "mongoc-cluster-sspi-private.h",
    "mongoc-cmd-private.h",
    "mongoc-collection-private.h",
    "mongoc-collection.h",
    "mongoc-compression-private.h",
    "mongoc-config.h.in",
    "mongoc-counters-private.h",
    "mongoc-crypt-private.h",
    "mongoc-crypto-cng-private.h",
    "mongoc-crypto-common-crypto-private.h",
    "mongoc-crypto-openssl-private.h",
    "mongoc-crypto-private.h",
    "mongoc-cursor-private.h",
    "mongoc-cursor.h",
    "mongoc-cyrus-private.h",
    "mongoc-database-private.h",
    "mongoc-database.h",
    "mongoc-deprioritized-servers-private.h",
    "mongoc-errno-private.h",
    "mongoc-error-private.h",
    "mongoc-error.h",
    "mongoc-find-and-modify-private.h",
    "mongoc-find-and-modify.h",
    "mongoc-flags-private.h",
    "mongoc-flags.h",
    "mongoc-generation-map-private.h",
    "mongoc-gridfs-bucket-file-private.h",
    "mongoc-gridfs-bucket-private.h",
    "mongoc-gridfs-bucket.h",
    "mongoc-gridfs-file-list-private.h",
    "mongoc-gridfs-file-list.h",
    "mongoc-gridfs-file-page-private.h",
    "mongoc-gridfs-file-page.h",
    "mongoc-gridfs-file-private.h",
    "mongoc-gridfs-file.h",
    "mongoc-gridfs-private.h",
    "mongoc-gridfs.h",
    "mongoc-handshake-compiler-private.h",
    "mongoc-handshake-os-private.h",
    "mongoc-handshake-private.h",
    "mongoc-handshake.h",
    "mongoc-host-list-private.h",
    "mongoc-host-list.h",
    "mongoc-http-private.h",
    "mongoc-init.h",
    "mongoc-interrupt-private.h",
    "mongoc-iovec.h",
    "mongoc-linux-distro-scanner-private.h",
    "mongoc-list-private.h",
    "mongoc-log-and-monitor-private.h",
    "mongoc-log-private.h",
    "mongoc-log.h",
    "mongoc-macros.h",
    "mongoc-memcmp-private.h",
    "mongoc-ocsp-cache-private.h",
    "mongoc-oidc-callback-private.h",
    "mongoc-oidc-callback.h",
    "mongoc-oidc-env-private.h",
    "mongoc-opcode.h",
    "mongoc-openssl-private.h",
    "mongoc-optional.h",
    "mongoc-opts-helpers-private.h",
    "mongoc-opts-private.h",
    "mongoc-prelude.h",
    "mongoc-queue-private.h",
    "mongoc-rand-private.h",
    "mongoc-rand.h",
    "mongoc-read-concern-private.h",
    "mongoc-read-concern.h",
    "mongoc-read-prefs-private.h",
    "mongoc-read-prefs.h",
    "mongoc-rpc-private.h",
    "mongoc-sasl-private.h",
    "mongoc-scram-private.h",
    "mongoc-secure-channel-private.h",
    "mongoc-secure-transport-private.h",
    "mongoc-server-api-private.h",
    "mongoc-server-api.h",
    "mongoc-server-description-private.h",
    "mongoc-server-description.h",
    "mongoc-server-monitor-private.h",
    "mongoc-server-stream-private.h",
    "mongoc-set-private.h",
    "mongoc-shared-private.h",
    "mongoc-sleep.h",
    "mongoc-socket-private.h",
    "mongoc-socket.h",
    "mongoc-ssl-private.h",
    "mongoc-ssl.h",
    "mongoc-sspi-private.h",
    "mongoc-stream-buffered.h",
    "mongoc-stream-file.h",
    "mongoc-stream-gridfs-download-private.h",
    "mongoc-stream-gridfs-upload-private.h",
    "mongoc-stream-gridfs.h",
    "mongoc-stream-private.h",
    "mongoc-stream-socket.h",
    "mongoc-stream-tls-openssl-bio-private.h",
    "mongoc-stream-tls-openssl-private.h",
    "mongoc-stream-tls-openssl.h",
    "mongoc-stream-tls-private.h",
    "mongoc-stream-tls-secure-channel-private.h",
    "mongoc-stream-tls-secure-channel.h",
    "mongoc-stream-tls-secure-transport-private.h",
    "mongoc-stream-tls-secure-transport.h",
    "mongoc-stream-tls.h",
    "mongoc-stream.h",
    "mongoc-structured-log-private.h",
    "mongoc-structured-log.h",
    "mongoc-thread-private.h",
    "mongoc-timeout-private.h",
    "mongoc-topology-background-monitoring-private.h",
    "mongoc-topology-description-apm-private.h",
    "mongoc-topology-description-private.h",
    "mongoc-topology-description.h",
    "mongoc-topology-private.h",
    "mongoc-topology-scanner-private.h",
    "mongoc-trace-private.h",
    "mongoc-ts-pool-private.h",
    "mongoc-uri-private.h",
    "mongoc-uri.h",
    "mongoc-util-private.h",
    "mongoc-version-functions.h",
    "mongoc-version.h.in",
    "mongoc-write-command-private.h",
    "mongoc-write-concern-private.h",
    "mongoc-write-concern.h",
    "mongoc.h",
    "service-gcp.h",
    "uthash.h",
    "utlist.h",
};

pub const mongo_src_files = &.{
    "mcd-azure.c",
    "mcd-nsinfo.c",
    "mcd-rpc.c",
    "mongoc-aggregate.c",
    "mongoc-apm.c",
    "mongoc-array.c",
    "mongoc-async-cmd.c",
    "mongoc-async.c",
    "mongoc-buffer.c",
    "mongoc-bulk-operation.c",
    "mongoc-bulkwrite.c",
    "mongoc-change-stream.c",
    "mongoc-client-pool.c",
    "mongoc-client-session.c",
    "mongoc-client-side-encryption.c",
    "mongoc-client.c",
    "mongoc-cluster-aws.c",
    "mongoc-cluster-cyrus.c",
    "mongoc-cluster-sasl.c",
    "mongoc-cluster-sspi.c",
    "mongoc-cluster.c",
    "mongoc-cmd.c",
    "mongoc-collection.c",
    "mongoc-compression.c",
    "mongoc-counters.c",
    "mongoc-crypt.c",
    "mongoc-crypto-cng.c",
    "mongoc-crypto-common-crypto.c",
    "mongoc-crypto-openssl.c",
    "mongoc-crypto.c",
    "mongoc-cursor-array.c",
    "mongoc-cursor-change-stream.c",
    "mongoc-cursor-cmd-deprecated.c",
    "mongoc-cursor-cmd.c",
    "mongoc-cursor-find-cmd.c",
    "mongoc-cursor-find-opquery.c",
    "mongoc-cursor-find.c",
    "mongoc-cursor-legacy.c",
    "mongoc-cursor.c",
    "mongoc-cyrus.c",
    "mongoc-database.c",
    "mongoc-deprioritized-servers.c",
    "mongoc-error.c",
    "mongoc-find-and-modify.c",
    "mongoc-flags.c",
    "mongoc-generation-map.c",
    "mongoc-gridfs-bucket-file.c",
    "mongoc-gridfs-bucket.c",
    "mongoc-gridfs-file-list.c",
    "mongoc-gridfs-file-page.c",
    "mongoc-gridfs-file.c",
    "mongoc-gridfs.c",
    "mongoc-handshake.c",
    "mongoc-host-list.c",
    "mongoc-http.c",
    "mongoc-init.c",
    "mongoc-interrupt.c",
    "mongoc-linux-distro-scanner.c",
    "mongoc-list.c",
    "mongoc-log-and-monitor-private.c",
    "mongoc-log.c",
    "mongoc-memcmp.c",
    "mongoc-ocsp-cache.c",
    "mongoc-opcode.c",
    "mongoc-openssl.c",
    "mongoc-optional.c",
    "mongoc-opts-helpers.c",
    "mongoc-opts.c",
    "mongoc-queue.c",
    "mongoc-rand-cng.c",
    "mongoc-rand-common-crypto.c",
    "mongoc-rand-openssl.c",
    "mongoc-read-concern.c",
    "mongoc-read-prefs.c",
    "mongoc-rpc.c",
    "mongoc-sasl.c",
    "mongoc-scram.c",
    "mongoc-secure-channel.c",
    "mongoc-secure-transport.c",
    "mongoc-server-api.c",
    "mongoc-server-description.c",
    "mongoc-server-monitor.c",
    "mongoc-server-stream.c",
    "mongoc-set.c",
    "mongoc-shared.c",
    "mongoc-socket.c",
    "mongoc-ssl.c",
    "mongoc-sspi.c",
    "mongoc-stream-buffered.c",
    "mongoc-stream-file.c",
    "mongoc-stream-gridfs-download.c",
    "mongoc-stream-gridfs-upload.c",
    "mongoc-stream-gridfs.c",
    "mongoc-stream-socket.c",
    "mongoc-stream-tls-openssl-bio.c",
    "mongoc-stream-tls-openssl.c",
    "mongoc-stream-tls-secure-channel.c",
    "mongoc-stream-tls-secure-transport.c",
    "mongoc-stream-tls.c",
    "mongoc-stream.c",
    "mongoc-structured-log.c",
    "mongoc-timeout.c",
    "mongoc-topology-background-monitoring.c",
    "mongoc-topology-description-apm.c",
    "mongoc-topology-description.c",
    "mongoc-topology-scanner.c",
    "mongoc-topology.c",
    "mongoc-ts-pool.c",
    "mongoc-uri.c",
    "mongoc-util.c",
    "mongoc-version-functions.c",
    "mongoc-write-command.c",
    "mongoc-write-concern.c",
    "service-gcp.c",
};
